@startuml
hide footbox

participant "Community Information Consumer" as Consumer
participant "Community Information Provider" as Provider

Consumer -> Provider : Community Information Delta Download Request
activate Provider
Provider --> Consumer : Community Information Delta Download Response
deactivate Provider

@enduml